import BossFight as bf1
import Cave as c1
import time
import os

class FinalArea:

  def __init__(self):
    pass

  def Beginning(self):
    os.system('clear||cls')
    print("Although you know you need to fight the evil wizard, you don't feel as if you are ready.")
    time.sleep(2)
    print("regardless, solomander is in danger, and you must save him.")
    time.sleep(2)
    print("You leave the old man's cave and begin moving towards the capital of the island")
    time.sleep(2)
    print("After two hours of running, you finally reach the capital city")
    time.sleep(2)
    print("You begin wondering where the wizard could be")
    time.sleep(2)
    print("You see two buildings that stand out among the rest")
    time.sleep(2)
    print("The first of the two is dark and gloomy, it immdediately makes you think of evil wizards.")
    time.sleep(2)
    print("The second building is a bright and colorful, it looks like a castle")
    time.sleep(2)
    print("You must choose which building to enter")
    time.sleep(2)
    go = input("1. Dark and Gloomy, /n2. Bright and Colorful")
    time.sleep(2)
    if go == "1":
      os.system('clear||cls')
      print("You decide to enter the dark and gloomy castle.")
      time.sleep(2)
      print("After entering, you realize it wasn't a dark and gloomy castle at all, but rather the IRS office")
      time.sleep(2)
      print("The IRS agents immediately recognize you because of your prominence on the MOST WANTED list for tax evasion")
      time.sleep(2)
      print("The IRS agents steal everything you own and you are forced to pay a tax of $1,000,000")
      time.sleep(2)
      if c1.sword == True:
        os.system('clear||cls')
        print("Your sword is taken away")
        bf1.playerdamage = 10
    elif go == "2":
      os.system('clear||cls')
      print("Although it looks like the wizard might be in the dark and gloomy castle, you can tell that he is really in the bright one")
      time.sleep(2)
      print("You enter the bright and colorful castle")
      time.sleep(2)
      print("The interior of the castle reminds you of the inside of an ikea")
      time.sleep(2)
      print("You begin walking deeper into the castle")
      time.sleep(2)
      print("You see two doors")
      time.sleep(2)
      print("The first is small, only tall enough for a midget to fit through")
      time.sleep(2)
      print('The other, giant, big enough for a giant')
      time.sleep(2)
      print("Both doors lead to seperate rooms, only one of which containing the wizard")
      time.sleep(2)
      print("Which door do you choose?")
      door = input("1. Small/n 2. Big")
      if door == "1":
        os.system('clear||cls')
        print("You break a hole in the wall above the small door beacause it is too small for you to fit through otherwise")
        time.sleep(2)
      print("The tall door disappears")
      time.sleep(2)
      print("You see the wizard sitting on his throne on the other side of the room")
      time.sleep(2)
      print("You challenge him")
      time.sleep(2)
      print("The wizard knew you would eventually show up")
      time.sleep(2)
      print("The wizard stands up")
      time.sleep(4)
      os.system('clear||cls')
      print("Although you should have guessed it by know, the wizard stands at a surprising 2 feet tall")
      time.sleep(2)
      print("Don't judge by his looks though, because he is still the most powerful wizard of current times")
      time.sleep(2)
      bf1.wizard()
      bf1.BossFight()
      time.sleep(2)
      print("After landing the last strike, the wizard falls to the ground")
      time.sleep(2)
      print("His body slowly turns into a black smoke")
      time.sleep(2)
      print("Where the wizard previously lay lies solomander, unharmed")
      time.sleep(2)
      print("There is also a gem laying on the ground beside solomander, it reminds you of the old man for some reason")
      time.sleep(4)
      os.system('clear||cls')
      print("Solomander has been saved")
      time.sleep(2)
      print("You aren't out of the woods yet, but you are safe")
      time.sleep(2)
      print("You leave the castle")
      time.sleep(2)
      print("With your sword in your hand, you begin the journey back home")
      time.sleep(2)
      print("You eventually arrive back at the cave, the old man waiting for you")
      time.sleep(2)
      print("You give him the gem you found at the castle")
      time.sleep(2)
      print("He thanks you, and tells you which way is the fastest")
      time.sleep(2)
      print("The old man said to head North")
      time.sleep(2)
      print("You were currently heading west")
      time.sleep(4)
      os.system('clear||cls')
      print("You head North")
      time.sleep(2)
      print("You travel through miles of thick forest, and eventually find a clearing")
      time.sleep(2)
      print("You found a bus station")
      time.sleep(2)
      print("This would have been smart to use on the way to the capital")
      time.sleep(2)
      print("You get on the first bus you see")
      time.sleep(2)
      print("There are two stops on the bus route, the airport and the port")
      time.sleep(2)
      print("The airport is the first stop and the port is the second")
      time.sleep(2)
      travelback = input("1. Airport, 2. Port")
      if travelback == "1":
        os.system('clear||cls')
        print("You travel to the airport")
        time.sleep(2)
        print("The workers at the airport give you a free plane ticket because you saved the island")
        time.sleep(2)
        print('The airline is called Malaysian Airlines')
        time.sleep(2)
        print("You go to gate 1B to get on your plane")
        time.sleep(2)
        print("The plane, surprisingly, arrives on time")
        time.sleep(2)
        print("You get on the plane and move to your seat")
        time.sleep(2)
        print("You decide to read more on your ticket because you are bored")
        time.sleep(2)
        print("The plane is called MH Airlines Flight 370")
        time.sleep(2)
        print("I wonder if that means anything")
        exit(0)
      elif travelback == "2":
        os.system('clear||cls')
        print("You decide to take a cruise back home")
        time.sleep(2)
        print("Probably a good idea because you have a round trip ticket")
        time.sleep(2)
        print("You arrive at the port")
        time.sleep(2)
        print("You get on the cruise")
        time.sleep(2)
        print("You spend the next week on the cruise")
        time.sleep(2)
        print("You and solomander enjoy it")
        time.sleep(2)
        print("You finally return to your home")
        time.sleep(2)
        print("You put solomander back in his box and go to sleep")
        time.sleep(2)
    elif door == "2":
      os.system('clear||cls')
      print("You push open the giant door")
      time.sleep(2)
      print("The tiny door disappears")
      time.sleep(2)
      print("You enter the giant room")
      time.sleep(2)
      print("The doors slam shut behind you")
      time.sleep(2)
      print("You hear a loud click")
      time.sleep(2)
      print("That must mean the doors locked")
      time.sleep(2)
      print("you look around the room")
      time.sleep(2)
      print("There is nothing in there")
      time.sleep(2)
      if bf1.magicuser == True:
        os.system('clear||cls')
        time.sleep(2)
        print("You remember that the old man taught you a destruction spell")
        time.sleep(2)
        print("You use it on the door")
        time.sleep(2)
        print("You escape the giant room")
        time.sleep(2)
        print("The small door has already dissapeared, meaning you cannot access the wizard")
        time.sleep(2)
        print("All hope for rescuing solomander is gone")
        time.sleep(2)
        print("You give up hope")
        exit(0)
      else:
        os.system('clear||cls')
        print("You are stuck in the room")
        time.sleep(2)
        print("You are unable to save solomander")
        exit(0)